### ISSUE TITLE
6-11 compile error

### ISSUE THREAD

**Issue by cczudianke** [bsmr-c-cpp/Cpp-Concurrency-in-Action#2]
when I compile this code, the compiler submit this error followed, I think it about template deduce error, but I can't find the error reason.

error: no viable conversion from
      returned value of type 'std::__1::__list_const_iterator<std::__1::pair<int,
      std::__1::basic_string<char> >, void *>' to function return type 'threadsafe_lookup_table<int,
      std::__1::basic_string<char>, std::__1::hash<int> >::bucket_type::bucket_iterator' (aka
      '__list_iterator<std::__1::pair<int, std::__1::basic_string<char> >, void *>')
            return std::find_if(data.begin(),data.end(), [&](bucket_value const& item)
                {return item.first==key;});

**Comment by bsmr** [comment]
I am sorry, I do not maintain this code. Maybe You should head over to https://www.manning.com/books/c-plus-plus-concurrency-in-action
